channels:
- conda-forge
dependencies:
- python=3.10.15
- pip<=24.2
- pip:
  - mlflow==2.14.3
  - cloudpickle==3.0.0
  - google-api-core==2.20.0
  - numpy==1.26.4
  - packaging==24.1
  - pandas==2.2.2
  - protobuf==4.25.5
  - psutil==6.0.0
  - pyyaml==6.0.1
  - scikit-learn==1.5.1
  - scipy==1.14.1
name: mlflow-env
