recipe: "regression/v1"
# Specifies the name of the column containing targets/labels for model training and evaluation
target_col: "Close"
# Specifies the value of `target_col` which is considered the positive class
positive_class: 1
# Sets the primary metric to use to evaluate model performance. This primary metric is used
# to sort MLflow Runs corresponding to the recipe in the MLflow Tracking UI
primary_metric: "mean_squared_error"
steps:
  ingest: {{INGEST_CONFIG}}
  split:
    split_ratios: [0.75, 0.125, 0.125]
  transform:
    using: custom
    # Specifies the method that defines the data cleaning process
    transformer_method: transformer_fn_regression
  train:
    using: custom
    # Specifies the method that defines the estimator type and parameters to use for model training
    estimator_method: estimator_fn_regression
  evaluate:
    # Sets performance thresholds that a trained model must meet in order to be eligible for
    # registration to the MLflow Model Registry
    validation_criteria:
      - metric: mean_squared_error
        threshold: 10
      - metric: r2_score
        threshold: 20

  register:
    # Indicates whether or not a model that fails to meet performance thresholds should still
    # be registered to the MLflow Model Registry
    allow_non_validated_model: false
  ingest_scoring: {{INGEST_SCORING_CONFIG}}
  predict:
    output: {{PREDICT_OUTPUT_CONFIG}}
    model_uri: "models/model.joblib"
